<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MainPageController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\RegisterAdminController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\ConferencesController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FloorManagerController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\PublicationController;
use App\Http\Controllers\FullpaperController;
use App\Http\Controllers\JKReviewerController;
use App\Http\Controllers\JKPendaftaranController;
use App\Http\Controllers\submissionStatusController;
use App\Http\Controllers\ReviewerController;
use App\Http\Controllers\PageEditController;
use App\Http\Controllers\JKTurnInController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\JKBendahariController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/',[MainPageController::class,'index']);
Route::post('/',[MainPageController::class,'button']);
Route::get('/registration',[RegistrationController::class,'index']);
Route::post('/registration',[RegistrationController::class,'store']);
Route::get('/login',[LoginController::class,'index']);
Route::post('/login',[LoginController::class,'check']);
Route::get('/homePage',[HomePageController::class,'index']);
Route::post('/homePage',[HomePageController::class,'logout']);
Route::get('/mainPage',[MainPageController::class,'index']);
Route::get('/index',[Controller::class,'index']);
Route::get('/adminRegister',[RegisterAdminController::class,'index']);
Route::post('/registerAdmin',[RegisterAdminController::class,'store']);
Route::get('/adminHomePage',[HomePageController::class,'index']);
Route::get('/superAdminHomePage',[HomePageController::class,'index']);
Route::get('/adminList',[SuperAdminController::class,'adminList'])->name('adminList');
Route::get('/logout',[LogoutController::class,'logout']);
Route::get('/conferencesInfo',[ConferencesController::class,'conferencesInfo']);
Route::get('/conferencesDownload',[ConferencesController::class,'conferencesDownload']);
Route::get('/faq',[FaqController::class,'index']);
Route::get('/faqVisitor',[FaqController::class,'visitor']);
Route::get('/publicationInfo',[PublicationController::class,'index']);
Route::get('/registerSubmission',[FullpaperController::class,'index']);
Route::post('/registerSubmission',[FullpaperController::class,'storeFullpaper']);
Route::get('/account',[AccountController::class,'index']);
Route::post('/updateProfile',[AccountController::class,'updateProfile'])->name('account.updateProfile');
Route::post('/updatePassword',[AccountController::class,'updatePassword'])->name('account.updatePassword');
Route::get('/participantsList',[SuperAdminController::class,'participantsList']);
Route::get('/forgotPassword',[ForgotPasswordController::class,'index']);
Route::post('/forgotPassword',[ForgotPasswordController::class,'sendOTP'])->name('forgotPasswordOTP');
Route::post('/forgotPasswordResendOTP',[ForgotPasswordController::class,'OTPSender'])->name('forgotPasswordResendOTP');
Route::get('/confirmOTP', [ForgotPasswordController::class,'indexConfirmOTP'])->name("confirmOTP");
Route::post('/confirmOTP', [ForgotPasswordController::class,'confirmOTP']);
Route::get('/changePassword', [ForgotPasswordController::class,'indexChangePassword']);
Route::post('/changePassword', [ForgotPasswordController::class,'changePassword']);
Route::get('/submissionStatus', [submissionStatusController::class,'index']);
Route::get('downloadSubmission/{filename}',  [submissionStatusController::class,'download'])->name('downloadSubmission');
Route::get('downloadJurnal/{filename}',  [PublicationController::class,'download'])->name('downloadJurnal');
Route::get('participants',  [SuperAdminController::class,'participantsList']);
Route::get('active/{adminEmail}',  [SuperAdminController::class,'activeAdmin'])->name('activeAdmin');
Route::get('deactive/{adminEmail}',  [SuperAdminController::class,'deactiveAdmin'])->name('deactiveAdmin');
Route::get('/JKReviewerHomePage',  [HomePageController::class,'index']);
Route::post('updateReviewer/{submissionCode}',  [JKReviewerController::class,'updateReviewer'])->name('updateReviewer');
Route::get('cancelReviewer/{submissionCode}',  [JKReviewerController::class,'cancelReviewer'])->name('cancelReviewer');
Route::get('/JkPendaftaranHomePage',[JKPendaftaranController::class,'index']);
Route::get('/JkPendaftaranHomePage',[HomePageController::class,'index']);
Route::get('/submissionList',  [JKPendaftaranController::class,'submissionList']);
Route::get('/ReviewerHomePage',[HomePageController::class,'index']);
Route::get('/pendingreview',  [ReviewerController::class,'pendingreviewlist']);
Route::get('/donereview',  [ReviewerController::class,'donereviewlist']);
Route::post('/upload/{submissionCode}', [ReviewerController::class,'uploadReviewSubmission'])->name('uploadReviewSubmission');
Route::get('downloadReviewedFile/{filename}',  [ReviewerController::class,'downloadReviewSubmission'])->name('downloadReviewedFile');
Route::get('conferencesDownload/{filename}',  [ConferencesController::class,'download'])->name('conferencesDownload');
Route::post('uploadReceipt/{submissionCode}', [submissionStatusController::class,'uploadReceipt'])->name('uploadReceipt');
Route::get('downloadPaymentReceipt/{proofOfPayment}', [submissionStatusController::class,'downloadPaymentReceipt'])->name('downloadPaymentReceipt');
Route::post('paymentStatusControl/{paymentID}', [JKBendahariController::class,'paymentStatusControl'])->name('paymentStatusControl');
Route::get('/pageList',[SuperAdminController::class,'pageList']);
Route::get('editPage/{page}', [PageEditController::class, 'editPage'])->name('editPage');
Route::post('/editPage/{pageName}', [PageEditController::class, 'saveEdit'])->name('saveEdit');
Route::get('evaluationForm/{submissionCode}', [ReviewerController::class, 'evaluationForm'])->name('evaluationForm');
Route::post('evaluationForm/{submissionCode}', [ReviewerController::class, 'submitEvaluationForm'])->name('evaluationForm');
Route::post('/uploadEvaluationForm/{submissionCode}', [ReviewerController::class,'uploadEvaluationForm'])->name('uploadEvaluationForm');
Route::get('downloadEvaluationForm/{filename}',  [ReviewerController::class,'downloadEvaluationForm'])->name('downloadEvaluationForm');
Route::post('/uploadTurnInReport/{submissionCode}', [JKTurnInController::class,'uploadTurnInReport'])->name('uploadTurnInReport');
Route::get('downloadTurnInReport/{filename}',  [JKTurnInController::class,'downloadTurnInReport'])->name('downloadTurnInReport');
Route::get('correctionForm/{submissionCode}',  [JKReviewerController::class,'correctionForm'])->name('correctionForm');
Route::post('/uploadNewCorrection/{submissionCode}', [JKReviewerController::class,'uploadNewCorrection'])->name('uploadNewCorrection');
Route::post('/uploadFileWithCorrection/{submissionCode}', [JKReviewerController::class,'uploadFileWithCorrection'])->name('uploadFileWithCorrection');
Route::get('downloadReturnCorrection/{filename}',  [JKReviewerController::class,'downloadReturnCorrection'])->name('downloadReturnCorrection');
Route::get('doneCorrection/{submissionCode}',  [JKReviewerController::class,'doneCorrection'])->name('doneCorrection');
Route::get('unDoneCorrection/{submissionCode}',  [JKReviewerController::class,'unDoneCorrection'])->name('unDoneCorrection');
Route::get('/gallery',[GalleryController::class,'index']);
Route::post('/pageEdit/Gallery/uploadNewPost',  [GalleryController::class,'uploadNewPost'])->name('uploadNewPost');
Route::post('/pageEdit/Gallery/editExistingPost/{id}',  [GalleryController::class,'editExistingPost'])->name('editExistingPost');
Route::post('/uploadParticipantsCertificate/{submissionCode}',  [JKReviewerController::class,'uploadParticipantsCertificate'])->name('uploadParticipantsCertificate');
Route::post('/uploadPresentationCertificate/{submissionCode}',  [JKReviewerController::class,'uploadPresentationCertificate'])->name('uploadPresentationCertificate');
Route::get('/downloadParticipantsCertificate/{filename}',  [JKReviewerController::class,'downloadParticipantsCertificate'])->name('downloadParticipantsCertificate');
Route::get('/downloadPresentationCertificate/{filename}',  [JKReviewerController::class,'downloadPresentationCertificate'])->name('downloadPresentationCertificate');
Route::get('/JKBendahariHomePage',[HomePageController::class,'index']);
Route::get('/paymentStatus',[JKBendahariController::class,'paymentStatus']);
Route::get('/feesPaymentQR',[JKBendahariController::class,'paymentQR']);
Route::post('/uploadNewPaymentQR',[JKBendahariController::class,'uploadNewPaymentQR'])->name('uploadNewPaymentQR');
Route::get('/removePaymentQR',[JKBendahariController::class,'removePaymentQR'])->name('removePaymentQR');
Route::get('/removePaymentDetails',[JKBendahariController::class,'removePaymentDetails'])->name('removePaymentDetails');
Route::get('/FloorManagerHomePage',[HomePageController::class,'index']);
Route::get('/reverseToLastEdition/{pageName}', [PageEditController::class, 'reversePage'])->name('reverseToLastEdition');
Route::get('/floorManager/presentationSchedule', [FloorManagerController::class, 'presentationSchedule'])->name('presentationSchedule');
Route::post('/floorManager/presentationSchedule/newSchedule', [FloorManagerController::class, 'uploadNewSchedule'])->name('newSchedule');
Route::post('/floorManager/presentationSchedule/editSchedule/{currentGroup}', [FloorManagerController::class, 'editSchedule'])->name('editSchedule');
Route::get('/floorManager/presentationSchedule/deleteSchedule/{group}', [FloorManagerController::class, 'deleteSchedule'])->name('deleteSchedule');
Route::get('/floorManager/presentationGroup', [FloorManagerController::class, 'presentationGroup'])->name('presentationGroup');
Route::post('/floorManager/presentationGroup/editSubmissionPresentationGroup/{submissionCode}', [FloorManagerController::class, 'editSubmissionPresentationGroup'])->name('editSubmissionPresentationGroup');
Route::get('/participants/presentationSchedule', [FloorManagerController::class, 'presentationSchedule']);
Route::get('/visitor/presentationSchedule', [FloorManagerController::class, 'presentationSchedule']);
Route::post('/superadmin/pageList/publicationList/editExistingPublication/{id}', [PublicationController::class, 'editExistingPublication'])->name('editExistingPublication');
Route::post('/superadmin/pageList/publicationList/uploadNewPublication', [PublicationController::class, 'uploadNewPublication'])->name('uploadNewPublication');
Route::post('/superadmin/pageList/conferencesDownload/editExistingConferencesDownload/{id}', [ConferencesController::class, 'editExistingConferencesDownload'])->name('editExistingConferencesDownload');
Route::post('/superadmin/pageList/conferencesDownload/uploadNewConferencesDownload', [ConferencesController::class, 'uploadNewConferencesDownload'])->name('uploadNewConferencesDownload');
Route::post('/registration/emailVerification',[RegistrationController::class,'OTPSender'])->name('emailVerification');
Route::post('/registration/validateOTP',[RegistrationController::class,'confirmOTP'])->name('emailVerification-confirmOTP');
Route::post('faq/submit',[FaqController::class, 'sendFaq'])->name('sendEmailContactUs');
Route::get('evaluationForm/generatePDFEvaluationForm/{id}',[ReviewerController::class, 'generatePDFEvaluationForm'])->name('generatePDFEvaluationForm');
Route::post('/superadmin/pageList/conferencesDownload/editExistingConferencesFees/{id}', [ConferencesController::class, 'editExistingConferencesFees'])->name('editExistingConferencesFees');
Route::post('/superadmin/pageList/conferencesDownload/editExistingConferencesDate/{id}', [ConferencesController::class, 'editExistingConferencesDate'])->name('editExistingConferencesDate');
Route::post('/superadmin/pageList/conferencesDownload/addNewConferencesDate', [ConferencesController::class, 'addNewConferencesDate'])->name('addNewConferencesDate');
Route::post('/superadmin/pageList/websiteLogo/editLogo/{id}', [SuperAdminController::class, 'editLogo'])->name('editLogo');
Route::post('/superadmin/submissionList/withdrawSubmission/{submissionCode}', [SuperAdminController::class, 'withdrawSubmission'])->name('withdrawSubmission');
Route::get('/bendahari/dashboard', [JKBendahariController::class, 'bendahariDashboard'])->name('bendahariDashboard');
Route::post('/JKReviewer/uploadCleanedDocument/{submissionCode}', [JKReviewerController::class, 'uploadCleanedDocument'])->name('uploadCleanedDocument');
Route::get('/downloadCleanedDocument/{filename}', [JKReviewerController::class, 'downloadCleanedDocument'])->name('downloadCleanedDocument');
Route::get('/superAdminHomePage',[SuperAdminController::class,'indexHomePage'])->name('superadminHomePage');
Route::get('/registerAsAudience',[FullpaperController::class,'indexRegisterAsAudience']);
Route::get('/recommendedSubmissionList',[JKReviewerController::class,'indexRecommendedSubmissionList'])->name('recommendedSubmissionList');
Route::get('/userManual',[MainPageController::class,'indexUserManual'])->name('userManual');
Route::post('/superAdminHomePage', [SuperAdminController::class, 'store'])->name('tasks.store');
Route::delete('/tasks/{id}', [SuperAdminController::class, 'destroy'])->name('tasks.destroy');